# freeze.py
import sys
import traceback
from flask_frozen import Freezer
# Import the Flask app instance from app/__init__.py
from app import app

# --- Configuration for GitHub Pages ---
# Sets the base URL. CRITICAL for links/CSS/JS on GitHub Pages.
# MUST match your repository name path.
print("Setting FREEZER_BASE_URL to '/'")
app.config['FREEZER_BASE_URL'] = '/'

# Sets the output directory for the static files
app.config['FREEZER_DESTINATION'] = 'build'
# Keep .nojekyll file if generated by GitHub Actions
app.config['FREEZER_REMOVE_EXTRA_FILES'] = False

# *** ADD THIS LINE TO FIX THE REDIRECT ISSUE ***
app.config['FREEZER_FOLLOW_REDIRECTS'] = True # Tell Frozen-Flask to follow 3xx redirects

# --- Handling Dynamic URLs (IMPORTANT LIMITATION) ---
# Static site generation CANNOT dynamically create pages for every possible
# block, transaction, or address. We MUST provide examples/placeholders
# for Frozen-Flask to generate the *structure* of these pages.
freezer = Freezer(app)

@freezer.register_generator
def transaction_urls():
    print("Generating static structure for /tx/<hash> using placeholder.")
    yield {'tx_hash': 'placeholder_tx_hash'}

@freezer.register_generator
def block_urls():
    print("Generating static structure for /block/<hash> using placeholder.")
    yield {'block_hash': 'placeholder_block_hash_or_number'}

@freezer.register_generator
def address_urls():
    print("Generating static structure for /address/<addr> using placeholder.")
    yield {'address': 'placeholder_address'}

# Main execution block for freezing
if __name__ == '__main__':
    print(f"Starting static site generation for pyExplorer...")
    print(f"Base URL: {app.config.get('FREEZER_BASE_URL', 'Not Set')}")
    print(f"Output directory: {app.config.get('FREEZER_DESTINATION', 'build')}")
    print(f"Follow Redirects: {app.config.get('FREEZER_FOLLOW_REDIRECTS', False)}")

    try:
        freezer.freeze()
        print(f"Static site generated successfully in '{app.config['FREEZER_DESTINATION']}'.")
        print("NOTE: Only placeholder pages were generated for dynamic routes (/tx, /block, /address).")
    except Exception as e:
        print(f"\nERROR during freezing process: {e}\n", file=sys.stderr)
        if isinstance(e, ValueError) and 'URL generator' in str(e):
            print("This often means a dynamic route exists in Flask", file=sys.stderr)
            print("but lacks a corresponding @freezer.register_generator", file=sys.stderr)
            print("function in freeze.py to provide placeholder values.", file=sys.stderr)
        traceback.print_exc()
        sys.exit(1) # Exit with error to fail the GitHub Action
