name: Docker Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Hub Login (Optional but Recommended)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Tag Docker Image
        run: |
          IMAGE_NAME=pymmdrza/pyexplorer
          IMAGE_TAG=latest
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

  push:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Docker Hub Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load Docker Image from Build Job
        run: docker load -i <(docker save ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }})

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
